 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.tabs;

import input.ChatReader;
import input.Message;
import java.util.ArrayDeque;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class SinglePastaTabPanel extends AbstractTabPanel {

    private String target = "";
    private long start = 0;
    private boolean set = false;
    private boolean found = false;
    private int pastaCount = 0;

    ArrayDeque<Long> kappaQ;

    /**
     * Creates new form SinglePastaTabPanel
     */
    public SinglePastaTabPanel(ChatReader cr) {
        super(cr);
        this.kappaQ = new ArrayDeque<Long>();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPastaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        currentPastaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pastaStatusLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pastaCountLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ppmLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastMinuteLabel = new javax.swing.JLabel();

        newPastaButton.setText("new pasta");
        newPastaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPastaButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("current pasta:");

        currentPastaField.setText("pasta not set");

        jLabel2.setText("pasta status:");

        pastaStatusLabel.setText("pasta not set");

        jLabel3.setText("Pasta count: ");

        pastaCountLabel.setText("0");

        jLabel4.setText("Pasta per minute:");

        ppmLabel.setText("0");

        jLabel5.setText("Pastas last minute:");

        lastMinuteLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newPastaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentPastaField, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pastaStatusLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pastaCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastMinuteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ppmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPastaButton)
                    .addComponent(jLabel1)
                    .addComponent(currentPastaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pastaStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pastaCountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lastMinuteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ppmLabel))
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newPastaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPastaButtonActionPerformed
        target = (String) JOptionPane.showInputDialog(new JFrame(), "Please enter your pasta: ", "Kappa");
        kappaQ = new ArrayDeque<Long>();
        this.currentPastaField.setText(target);
        this.start = new Date().getTime();
        this.cr.sendMessage(target, cr.currentChannels.get(0));
        set = true;
        this.pastaStatusLabel.setText("PASTA NOT FOUND YET");
        this.lastMinuteLabel.setText("0");
        this.ppmLabel.setText("0");
        this.pastaCountLabel.setText("0");
        this.found = false;
        this.pastaCount = 0;
    }//GEN-LAST:event_newPastaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentPastaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lastMinuteLabel;
    private javax.swing.JButton newPastaButton;
    private javax.swing.JLabel pastaCountLabel;
    private javax.swing.JLabel pastaStatusLabel;
    private javax.swing.JLabel ppmLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onMessage(Message message) {

        if (set && message.getMsg().contains(target)) {
            if (!found) {
                this.pastaStatusLabel.setText("PASTA FOUND IN " + (new Date().getTime() - this.start));
                found = true;
            }
            this.pastaCount++;
            this.pastaCountLabel.setText(this.pastaCount + "");
            this.kappaQ.add((Long) System.currentTimeMillis());
        }
        if (!kappaQ.isEmpty()) {
            while (kappaQ.getFirst() < System.currentTimeMillis() - 60000) {
                kappaQ.removeFirst();
                if (kappaQ.isEmpty()) {
                    break;
                }
            }
        }
        this.lastMinuteLabel.setText(kappaQ.size() + "");
        this.ppmLabel.setText(this.pastaCount / ((System.currentTimeMillis() - start + 1.0) / 60000) + "");
    }

    @Override
    public void onUserMessage(Message message) {
        //kdyz se zavola cr.sendMessage
    }
}
